# Generated by Django 4.1.4 on 2023-01-04 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catalogue_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='id',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
