# Generated by Django 4.1.4 on 2023-01-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_catalogue_id_alter_catalogue_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='temp_id',
            new_name='id',
        ),
    ]
